name: data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.COMPAT_BOT_TOKEN }}
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: yarn install
        run: yarn install --immutable

      - name: mdn/browser-compat-data
        run: yarn up '@mdn/browser-compat-data@>=5.1.0 <6.0.0'

      - name: content update/run.js
        run: |
          pushd packages/content
          rm -fr @content
          node update/run.js
          popd

      - name: codegen
        run: yarn codegen

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(data): update data'
          commit_user_name: compatbot
          commit_user_email: 102001024+compatbot@users.noreply.github.com
          commit_author: compatbot <102001024+compatbot@users.noreply.github.com>
          branch: main
